apiVersion: v1
kind: Service
metadata:
        name: djangoservice
spec:
        selector:
             app: djangoapp
        ports:
             - protocol: TCP
               port: 80
               targetPort: 8000
        type: LoadBalancer
